# Generated by Django 3.0.3 on 2020-02-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juheapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='focus_city',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='user',
            name='focus_constellation',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='user',
            name='focus_stock',
            field=models.TextField(default='[]'),
        ),
    ]
