# Generated by Django 3.0.3 on 2020-02-27 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juheapp', '0002_auto_20200227_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='focus_city',
            new_name='focus_cities',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='focus_constellation',
            new_name='focus_constellations',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='focus_stock',
            new_name='focus_stocks',
        ),
    ]
