publish:
    - app:
          name: 微信
          发布日期: 20180101
          版本: 1.0
    - app:
        name: 支付宝
        发布日期: 20180101
        版本: 1.0
    - app:
        name: QQ
        发布日期: 20180101
        版本: 1.0
    - app:
        name: 钉钉
        发布日期: 20180101
        版本: 1.0
    - app:
          name: 笑话展现
          发布日期: 20200124
          版本: 1.0
develope:
    - app: